default:
  image: python:3.9

stages:
  - Unit tests
  - Publish

before_script:
  - pip3 install poetry
  - poetry install

testing:
  stage: Unit tests
  script:
    - poetry run python3 -u -m pytest --cov=git_prune --cov-report=xml:coverage.xml --junitxml=report.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

publish:
  stage: Publish
  script:
    - poetry config repositories.gitlab https://gitlab.richardsoper.me/api/v4/projects/40/packages/pypi
    - poetry publish --repository gitlab -u gitlab-ci-token -p $CI_JOB_TOKEN --build
    - poetry publish -u __token__ -p $PYPI_KEY
  only:
    - main
