default:
  image: python:3.9

stages:
  - Unit tests
  - Test build
  - Publish

before_script:
  - pip3 install poetry
  - poetry install

testing:
  stage: Unit tests
  script:
    - poetry run python3 -u -m pytest --cov=git_prune --cov-report=xml:coverage.xml --junitxml=report.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

test-build:
  stage: Test build
  script:
    - poetry build

publish:
  variables:
    PYPI: $pypi
  stage: Publish
  script:
    - poetry publish -u __token__ -p $PYPI --build
  only:
    - master
    - main
